# Generated by Django 4.1.2 on 2022-11-15 03:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('DateApplied', models.DateField(blank=True, default=datetime.datetime.today)),
                ('RecruiterName', models.CharField(max_length=30)),
                ('RecruiterEmail', models.EmailField(max_length=254)),
                ('Status', models.CharField(max_length=200)),
                ('ApplicationNotes', models.CharField(blank=True, max_length=1000)),
                ('EstimatedSalary', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('ResumePDF', models.FileField(blank=True, upload_to='uploads/')),
                ('ApplicationCreator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
