# Generated by Django 4.1.2 on 2022-12-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptrackpages', '0004_client_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name_plural': 'applications'},
        ),
        migrations.AlterModelTable(
            name='application',
            table='application',
        ),
    ]
